spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lti_ats
    username: lti_user
    password: lti_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
